version: '3.7'

services:
  web:
    build: .
    command:  sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn beautiful_slovenia.wsgi:application --bind 0.0.0.0:8000 --reload -w 4"
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/static
    ports:
      - "8100:8100"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=debt_user
      - POSTGRES_PASSWORD=haeryr^sdf^dfg
      - POSTGRES_DB=debt
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "444:444"
    depends_on:
      - web
    volumes:
      - ./nginx/cert:/etc/ssl/cert
      - static_volume:/usr/src/app/static
volumes:
  postgres_data:
  static_volume: